#ifndef KEYMAP_H
#define KEYMAP_H

#include "types.h"

static u8 key_modifiers = 0;

enum key_modifiers {
  SHIFT_MODIFIER = 1,
  ALT_MODIFIER = 2,
  CTRL_MODIFIER = 0
};

enum keys {
  KEY_NULL = 0x00,
  KEY_CAPS = 0x01,
  KEY_HOME = 0x02,
  KEY_END = 0x03,
  KEY_F1 = 0x04,
  KEY_F2 = 0x05,
  KEY_F3 = 0x06,
  KEY_F4 = 0x07,
  KEY_BACKSPACE = 0x08,
  KEY_TAB = 0x09,
  KEY_ENTER = 0x0A,
  KEY_CTRL = 0x0B,


  KEY_LSHIFT = 0x0E,
  KEY_RSHIFT = 0x0F,
  KEY_F5 = 0x10,
  KEY_F6 = 0x11,
  KEY_F7 = 0x12,
  KEY_F8 = 0x13,
  KEY_F9 = 0x14,
  KEY_F10 = 0x15,
  KEY_F11 = 0x16,
  KEY_F12 = 0x17,
  KEY_VERNUM = 0x18,
  KEY_SCROLL_LOCK = 0x19,
  KEY_ALT = 0x1A,
  KEY_ESCAPE = 0x1B,
  KEY_UP = 0x1C,
  KEY_DOWN = 0x1D,
  KEY_LEFT = 0x1E,
  KEY_RIGHT = 0x1F,

  KEY_DELETE = 0x7F,
  KEY_PAGE_DOWN = 0x81,
  KEY_PAGE_UP = 0x8D,
  KEY_INSERT = 0x8F,
  KEY_ALT_SYSREQ = 0x90
};

struct key {
  u8 primary, secondary, alt, secondary_alt;
} __attribute__((packed)) keymap[128] = {
  {KEY_NULL},
  {KEY_NULL},
  {'&', '1', KEY_NULL, KEY_NULL},
  { 0xE9/* é */, '2', '~', KEY_NULL},
  { '"', '3', '#', KEY_NULL },
  { '\'', '4', '{', KEY_NULL },
  { '(', '5', '[', KEY_NULL },
  { '-', '6', '|', KEY_NULL },
  { 0xE8/* è */, '7', '`', KEY_NULL },
  { '_', '8', '\\', KEY_NULL },
  { 0xE7/* ç */, '9', '^', KEY_NULL },
  { 0xE0/* à */, '0', '@', KEY_NULL },
  { ')', '°', ']', KEY_NULL },
  { '=', '+', '}', KEY_NULL },
  { KEY_BACKSPACE, KEY_BACKSPACE, KEY_NULL, KEY_NULL },
  { KEY_TAB, KEY_TAB, KEY_NULL, KEY_NULL },
  { 'a', 'A', KEY_NULL, KEY_NULL },
  { 'z', 'Z', KEY_NULL, KEY_NULL },
  { 'e', 'E', KEY_NULL, KEY_NULL },
  { 'r', 'R', KEY_NULL, KEY_NULL },
  { 't', 'T', KEY_NULL, KEY_NULL },
  { 'y', 'Y', KEY_NULL, KEY_NULL },
  { 'u', 'U', KEY_NULL, KEY_NULL },
  { 'i', 'I', KEY_NULL, KEY_NULL },
  { 'o', 'O', KEY_NULL, KEY_NULL },
  { 'p', 'P', KEY_NULL, KEY_NULL },
  { '^', 0xA8/* ¨ */, KEY_NULL, KEY_NULL },
  { '$', 0xA3/* £ */, KEY_NULL, KEY_NULL },
  { KEY_ENTER, KEY_ENTER, KEY_NULL, KEY_NULL },
  { KEY_CTRL, KEY_CTRL, KEY_NULL, KEY_NULL },
  { 'q', 'Q', KEY_NULL, KEY_NULL },
  { 's', 'S', KEY_NULL, KEY_NULL },
  { 'd', 'D', KEY_NULL, KEY_NULL },
  { 'f', 'F', KEY_NULL, KEY_NULL },
  { 'g', 'G', KEY_NULL, KEY_NULL },
  { 'h', 'H', KEY_NULL, KEY_NULL },
  { 'j', 'J', KEY_NULL, KEY_NULL },
  { 'k', 'K', KEY_NULL, KEY_NULL },
  { 'l', 'L', KEY_NULL, KEY_NULL },
  { 'm', 'M', KEY_NULL, KEY_NULL },
  { 0xF9/* ù */, '%', KEY_NULL, KEY_NULL },
  { '?', '?', KEY_NULL, KEY_NULL },
  { KEY_LSHIFT, KEY_LSHIFT, KEY_NULL, KEY_NULL },
  { '*', 0xB5/* µ */, 0xF8/* ø */, KEY_NULL },
  { 'w', 'W', KEY_NULL, KEY_NULL },
  { 'x', 'X', KEY_NULL, KEY_NULL },
  { 'c', 'C', KEY_NULL, KEY_NULL },
  { 'v', 'V', KEY_NULL, KEY_NULL },
  { 'b', 'B', KEY_NULL, KEY_NULL },
  { 'n', 'N', KEY_NULL, KEY_NULL },
  { ',', '?', KEY_NULL, KEY_NULL },
  { ';', '.', KEY_NULL, KEY_NULL },
  { ':', '/', KEY_NULL, KEY_NULL },
  { '!', '§', KEY_NULL, KEY_NULL },
  { KEY_RSHIFT, KEY_RSHIFT, KEY_NULL, KEY_NULL },
  { '*', KEY_NULL, KEY_NULL, KEY_NULL },
  { KEY_ALT, KEY_ALT, KEY_ALT, KEY_NULL },
  { ' ', ' ', KEY_NULL, KEY_NULL },
  { KEY_CAPS, KEY_CAPS, KEY_NULL, KEY_NULL },
  { KEY_F1, KEY_F1, KEY_NULL, KEY_NULL },
  { KEY_F2, KEY_F2, KEY_NULL, KEY_NULL },
  { KEY_F3, KEY_F3, KEY_NULL, KEY_NULL },
  { KEY_F4, KEY_F4, KEY_NULL, KEY_NULL },
  { KEY_F5, KEY_F5, KEY_NULL, KEY_NULL },
  { KEY_F6, KEY_F6, KEY_NULL, KEY_NULL },
  { KEY_F7, KEY_F7, KEY_NULL, KEY_NULL },
  { KEY_F8, KEY_F8, KEY_NULL, KEY_NULL },
  { KEY_F9, KEY_F9, KEY_NULL, KEY_NULL },
  { KEY_F10, KEY_F10, KEY_NULL, KEY_NULL },
  { KEY_VERNUM, KEY_VERNUM, KEY_NULL, KEY_NULL },
  { KEY_SCROLL_LOCK, KEY_SCROLL_LOCK, KEY_NULL, KEY_NULL },
  { '7', KEY_HOME, KEY_NULL, KEY_NULL },
  { '8', KEY_UP, KEY_NULL, KEY_NULL },
  { '9', KEY_PAGE_UP, KEY_NULL, KEY_NULL },
  { '-', KEY_NULL, KEY_NULL, KEY_NULL },
  { '4', KEY_LEFT, KEY_NULL, KEY_NULL },
  { '5', KEY_NULL, KEY_NULL, KEY_NULL },
  { '6', KEY_RIGHT, KEY_NULL, KEY_NULL },
  { '+', KEY_NULL, KEY_NULL, KEY_NULL },
  { '1', KEY_END, KEY_NULL, KEY_NULL },
  { '2', KEY_DOWN, KEY_NULL, KEY_NULL },
  { '3', KEY_PAGE_DOWN, KEY_NULL, KEY_NULL },
  { '0', KEY_INSERT, KEY_NULL, KEY_NULL },
  { '.', KEY_DELETE, KEY_NULL, KEY_NULL }, // KEY_DELETE, KEY_INSERT
  { KEY_ALT_SYSREQ, KEY_ALT_SYSREQ, KEY_ALT_SYSREQ, KEY_NULL },
  { KEY_NULL, KEY_NULL, KEY_NULL, KEY_NULL },
  { '<', '>', KEY_NULL, KEY_NULL },
  { KEY_F11, KEY_F11, KEY_NULL, KEY_NULL },
  { KEY_F12, KEY_F12, KEY_NULL, KEY_NULL },
};


#endif // KEYMAP_H